# Generated by Django 4.2.13 on 2024-06-26 13:28

from django.db import migrations, models
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_pgvector_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_vectors', pgvector.django.vector.VectorField(blank=True, null=True)),
            ],
        ),
    ]
